$(document).ready(function(){
	$("#btnContact").click(function(){
	    $("#middelContent").hide();
	    $("#contactContent").show();
	});
	
	$("#portfolio").click(function(){
	    $("#middelContent").hide();
	    $("#contactContent").hide();
	    $("#sp").hide();
	    $("#reso").hide();
	    $("#port").show();
	});
	$("#resources").click(function(){
	    $("#middelContent").hide();
	    $("#contactContent").hide();
	    $("#port").hide();
	    $("#sp").hide();
	    $("#reso").show();
	});
	$("#spm").click(function(){
	    $("#middelContent").hide();
	    $("#contactContent").hide();
	    $("#port").hide();
	    $("#reso").hide();
	    $("#sp").show();
	});
});